language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
services:
  - postgresql
# command to install dependencies
#source venv/bin/activate
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py makemigrations music
  - python manage.py migrate
  - DJANGO_SUPERUSER_USERNAME=nrweerad \
  - DJANGO_SUPERUSER_PASSWORD=nrweerad \
  - python manage.py createsuperuser --noinput
  - python manage.py runserver
